name: 抖音视频同步到飞书

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      feishu_table_url:
        description: '飞书多维表格链接'
        required: true
        type: string
      feishu_auth_token:
        description: '飞书多维表格授权码'
        required: true
        type: string
      douyin_url:
        description: '抖音用户主页URL'
        required: true
        type: string
      max_videos:
        description: '最大视频数量'
        required: false
        default: '20'
        type: string
  
  # HTTP API 触发
  repository_dispatch:
    types: [douyin-sync]

jobs:
  sync-douyin-videos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo "=== 安装依赖前的包列表 ==="
        pip list
        echo "=== 开始安装requirements.txt ==="
        pip install -r requirements.txt
        echo "=== 安装依赖后的包列表 ==="
        pip list
        echo "=== 测试关键模块导入 ==="
        python -c "import requests; print('✓ requests导入成功')"
        python -c "import dotenv; print('✓ dotenv导入成功')"
        python -c "from douyin_scraper import DouyinScraper; print('✓ DouyinScraper导入成功')"
    
    - name: Create .env file
      run: |
        echo "FEISHU_APP_ID=${{ secrets.FEISHU_APP_ID }}" >> .env
        echo "FEISHU_APP_SECRET=${{ secrets.FEISHU_APP_SECRET }}" >> .env
        # 从多维表格链接中提取APP_TOKEN和TABLE_ID
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          TABLE_URL="${{ github.event.inputs.feishu_table_url }}"
          AUTH_TOKEN="${{ github.event.inputs.feishu_auth_token }}"
        else
          TABLE_URL="${{ github.event.client_payload.feishu_table_url }}"
          AUTH_TOKEN="${{ github.event.client_payload.feishu_auth_token }}"
        fi
        # 从URL中提取APP_TOKEN (格式: https://xxx.feishu.cn/base/APP_TOKEN?table=TABLE_ID)
        APP_TOKEN=$(echo "$TABLE_URL" | sed -n 's/.*\/base\/\([^?]*\).*/\1/p')
        TABLE_ID=$(echo "$TABLE_URL" | sed -n 's/.*table=\([^&]*\).*/\1/p')
        echo "FEISHU_APP_TOKEN=$APP_TOKEN" >> .env
        echo "FEISHU_TABLE_ID=$TABLE_ID" >> .env
        echo "FEISHU_PERSONAL_BASE_TOKEN=$AUTH_TOKEN" >> .env
    
    - name: Run douyin sync (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "=== 运行前环境检查 ==="
        python --version
        which python
        echo "当前目录: $(pwd)"
        ls -la
        echo "=== 环境变量 ==="
        env | grep -E "(DOUYIN|MAX_VIDEOS|FEISHU)" || echo "未找到相关环境变量"
        echo "=== GitHub Actions 环境检测 ==="
        echo "GITHUB_ACTIONS=${GITHUB_ACTIONS}"
        echo "RUNNER_OS=${RUNNER_OS}"
        echo "RUNNER_ARCH=${RUNNER_ARCH}"
        echo "=== 网络连接测试 ==="
        curl -I https://www.douyin.com/ || echo "无法连接到抖音"
        echo "=== 开始运行主脚本 ==="
        export GITHUB_ACTIONS=true
        python main.py --url "${{ github.event.inputs.douyin_url }}" --max-videos "${{ github.event.inputs.max_videos }}"
    
    - name: Run douyin sync (API trigger)
      if: github.event_name == 'repository_dispatch'
      run: |
        echo "=== 运行前环境检查 ==="
        python --version
        which python
        echo "当前目录: $(pwd)"
        ls -la
        echo "=== 环境变量 ==="
        env | grep -E "(DOUYIN|MAX_VIDEOS|FEISHU)" || echo "未找到相关环境变量"
        echo "=== GitHub Actions 环境检测 ==="
        echo "GITHUB_ACTIONS=${GITHUB_ACTIONS}"
        echo "RUNNER_OS=${RUNNER_OS}"
        echo "RUNNER_ARCH=${RUNNER_ARCH}"
        echo "=== 网络连接测试 ==="
        curl -I https://www.douyin.com/ || echo "无法连接到抖音"
        echo "=== 开始运行主脚本 ==="
        export GITHUB_ACTIONS=true
        DOUYIN_URL="${{ github.event.client_payload.douyin_url }}"
        MAX_VIDEOS="${{ github.event.client_payload.max_videos }}"
        if [ -z "$MAX_VIDEOS" ]; then
          MAX_VIDEOS="20"
        fi
        python main.py --url "$DOUYIN_URL" --max-videos "$MAX_VIDEOS"
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sync-logs
        path: feishu_sync.log