name: 抖音视频同步到飞书

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      douyin_url:
        description: '抖音用户主页URL'
        required: true
        type: string
      max_videos:
        description: '最大视频数量'
        required: false
        default: '20'
        type: string
  
  # HTTP API 触发
  repository_dispatch:
    types: [douyin-sync]

jobs:
  sync-douyin-videos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "FEISHU_APP_ID=${{ secrets.FEISHU_APP_ID }}" >> .env
        echo "FEISHU_APP_SECRET=${{ secrets.FEISHU_APP_SECRET }}" >> .env
        echo "FEISHU_APP_TOKEN=${{ secrets.FEISHU_APP_TOKEN }}" >> .env
    
    - name: Run douyin sync (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: |
        python main.py "${{ github.event.inputs.douyin_url }}" --max-videos "${{ github.event.inputs.max_videos }}"
    
    - name: Run douyin sync (API trigger)
      if: github.event_name == 'repository_dispatch'
      run: |
        DOUYIN_URL="${{ github.event.client_payload.douyin_url }}"
        MAX_VIDEOS="${{ github.event.client_payload.max_videos }}"
        if [ -z "$MAX_VIDEOS" ]; then
          MAX_VIDEOS="20"
        fi
        python main.py "$DOUYIN_URL" --max-videos "$MAX_VIDEOS"
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: sync-logs
        path: feishu_sync.log